#!/usr/bin/env node
/**
 * generate-stories.mjs — scaffolds minimal CSF3 stories for components that
 * lack one, so the computed-style extractor can render every component.
 * Idempotent: never overwrites an existing story. Auto-generated files carry a
 * header marker so they are easy to grep and remove later.
 *
 *   node generate-stories.mjs            # dry run, lists what's missing
 *   node generate-stories.mjs --write    # writes the .stories files
 */
import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const WRITE = process.argv.includes("--write");
const readJSON = (p) => { try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; } };
const fw = readJSON(path.join(ROOT, "design-audit", "framework.json")) ||
  { framework: "react", componentExts: [".tsx", ".jsx"], srcDirs: ["src"] };
const exts = fw.componentExts || [".tsx", ".jsx"];
const MARKER = "// AUTO-GENERATED by css-drift-auditor — safe to delete after audit";

function walk(dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".") || e.name === "node_modules") continue;
    const f = path.join(dir, e.name);
    if (e.isDirectory()) walk(f, acc); else acc.push(f);
  }
  return acc;
}

const isStory = (f) => /\.stories\.[jt]sx?$|\.stories\.(vue|svelte)$/.test(f);
const exportsSomething = (f) => { try { return /export\s+(default|const|function)\s/.test(fs.readFileSync(f, "utf8")); } catch { return false; } };
const isComponent = (f) => {
  const base = path.basename(f);
  if (isStory(f) || /\.(test|spec|d)\.[jt]sx?$/.test(base)) return false;
  if (!/^[A-Z]/.test(base)) return false;
  if (fw.framework === "svelte") return base.endsWith(".svelte");
  if (fw.framework === "vue") return base.endsWith(".vue");
  return exts.some((x) => base.endsWith(x)) && exportsSomething(f);
};

const dirs = (fw.srcDirs?.length ? fw.srcDirs : ["src", "components", "app"]).map((d) => path.join(ROOT, d));
const all = [...new Set(dirs.flatMap((d) => walk(d)))];
const existing = new Set(
  all.filter(isStory).map((f) =>
    path.basename(f).replace(/\.stories\.[jt]sx?$/, "").replace(/\.stories\.(vue|svelte)$/, ""))
);

const components = all.filter(isComponent);
const missing = components.filter((c) => !existing.has(path.basename(c).replace(/\.[^.]+$/, "")));

console.log(`\n📚 ${components.length} components · ${existing.size} have stories · ${missing.length} missing\n`);

const reactStory = (name, imp) =>
  `${MARKER}\nimport ${name} from '${imp}';\n\nexport default { title: 'Audit/${name}', component: ${name} };\n\nexport const Default = {};\n`;
const vueStory = (name, imp) =>
  `${MARKER}\nimport ${name} from '${imp}';\nexport default { title: 'Audit/${name}', component: ${name} };\nexport const Default = { render: () => ({ components: { ${name} }, template: '<${name} />' }) };\n`;

let written = 0;
for (const comp of missing) {
  const name = path.basename(comp).replace(/\.[^.]+$/, "");
  const dir = path.dirname(comp);
  const storyExt = fw.framework === "vue" ? ".stories.js" : (exts[0].includes("ts") ? ".stories.tsx" : ".stories.jsx");
  const storyPath = path.join(dir, name + storyExt);
  const imp = "./" + path.basename(comp).replace(/\.(tsx?|jsx?|vue|svelte)$/, "");
  const content = fw.framework === "vue" ? vueStory(name, imp) : reactStory(name, imp);
  console.log(`  ${WRITE ? "+ " : "(dry) "}${path.relative(ROOT, storyPath)}`);
  if (WRITE && !fs.existsSync(storyPath)) { fs.writeFileSync(storyPath, content); written++; }
}

console.log(`\n${WRITE ? `✓ wrote ${written} stories` : "Dry run — pass --write to create these"}`);
console.log("  Note: components with required props may fail to render; refine those few by hand.\n");
